<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>


<div id="adm-stw-top-container" style="padding-top: 80px"></div>
<div class="description" id="block-description">
	<h1><?php echo $this->__('Invitations sent') ?></h1>
	<h2><?php echo $this->__('You have successfully invited your friends!') ?></h2>
	<div class="adm-stw-information">
		<?php if($this->canShowDiscountContainer()) { ?>
		<p class="adm-stw-discount-information round">
			<strong><?php echo $this->__('Your %s Discount Code:', $this->getDiscountAmount()) ?></strong><span class="adm-stw-discount-code"><?php echo $this->getCouponCode(); ?></span>
		</p>
		<?php if($this->canExpire()) { ?>
		<p class="adm-stw-discount-terms">
			<strong><?php echo $this->__('Expiration Date:') ?></strong> <?php echo $this->getExpire(); ?>
		</p>
		<?php } ?>
		<?php if($this->haveConditions()) { ?>
		<p class="adm-stw-discount-terms">
			<strong><?php echo $this->__('Other Discount Terms:') ?></strong> <?php echo $this->__('please contact the store owner for more information.')?>
		</p>
		<?php } ?>
		<?php if($this->isSent()) { ?>
		<p style="font-size: 11px; color: #777;"><?php echo $this->__('A confirmation has been sent to your email address.') ?></p>
		<?php } ?>
		<p class="adm-stw-discount-action">
			<span class="adm-stw-download-discount"><a title="<?php echo $this->__('Download the discount information as a text file for future reference.') ?>" href="<?php echo $this->getDownloadUrl(); ?>"><?php echo $this->__('Download discount information') ?></a></span>
			<?php if($this->canApplyNow()) { ?>
			<span class="adm-stw-apply-discount"><a title="<?php echo $this->__('Apply this discount to your cart right now.') ?>" href="<?php echo $this->getUrl('checkout/cart/couponPost', array('coupon_code' => $this->getCouponCode())) ?>" target="_blank"><?php echo $this->__('Apply the discount now') ?></a></span>
			<?php } ?>
		</p>
		<?php } else { ?>
		<p><?php echo $this->__('We thank you for inviting your friends to our store!') ?></p>
		<p><?php echo $this->__('We sincerely hope that you and your close friends will be satisfied with the level of our service.') ?></p>
		<?php } ?>
	</div>
</div>