<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */


$stats = $this->getStats();
$service = $this->getServiceName();
$is_manual_mode = $this->isManualInvitation();

?>
<div class="services" id="services">
	<ul class="adm-stw-stats round">
		<li class="adm-stw-stats-header"><strong><?php echo $this->__('%s Invitation Stats', $service) ?></strong></li>
		<li class="adm-stw-stats-data"><strong><?php echo $stats['imported'] ?></strong><?php echo $this->__('Imported') ?></li>
	<?php if(! $is_manual_mode) { ?>
	<li class="adm-stw-stats-data"><strong><?php echo $stats['checked'] ?></strong><?php echo $this->__('Selected') ?></li>
	<?php } ?>
	<li class="adm-stw-stats-data"><strong><?php echo (isset($stats['skipped'])) ? $stats['skipped'] : '0'; ?></strong><?php echo $this->__('Skipped') ?></li>
		<li class="adm-stw-stats-data"><strong><?php echo $stats['success'] ?></strong><?php echo $this->__('Total Invited') ?></li>
	</ul>
</div>