<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>

<?php $data = Mage::getSingleton('customer/session')->getStwCaptcha(); ?>
<div class="services" id="services">
	<div class="round service-view" id="verifier">
		<div class="round container-active adm-stw-captcha-container" id="container">
			<div>
				<div class="top-left"><?php echo $this->__('Captcha Verification'); ?></div>
				<div class="top-right">
					<span><?php echo $this->__('messages left:'); ?></span> <?php echo count($data['recipients']); ?></div>
				<div class="view-container">
					<div class="fix">
				<?php echo $this->__('Captcha verification is required. To continue sending messages, please enter the code you see on the picture.'); ?>
				<div class="separator"></div>
						<div class="form-container">
							<form id="verifier_data" class="form-list" action="<?php echo $this->getUrl('*/captchaverifier') ?>" method="post">
								<table>
									<tbody>
										<tr>
											<th></th>
											<td class="adm-stw-captcha"><img src="<?php echo $data['captcha_img'] ?>" /></td>
										</tr>
										<tr>
											<th><label class="required"><em>*</em><?php echo $this->__('Code:'); ?></label></th>
											<td><input type="text" name="captcha_sid" class="input-text required-entry" title="Code"></td>
										</tr>
										<tr>
											<th></th>
											<td>
												<button type="submit" onclick="stwProcessData('verifier_data')" title="<?php echo $this->__('Continue'); ?>" id="find-friends">
													<span><span><?php echo $this->__('Continue'); ?></span></span>
												</button>
											</td>
										</tr>
									</tbody>
								</table>
								<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
