<?php
//$_productCollection=$this->getLoadedProductCollection();

// list all products
//$_productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToFilter("lr_content_type",   array('neq' => 3,))->addAttributeToSort('entity_id', 'DESC')->setPageSize(1);
$_productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSort('entity_id', 'DESC')->setPageSize(10);

foreach ($_productCollection as $_p){
  $label = $this->helper('shoppersettings')->getLabel($_p);  // s
  if( $_p->getData("lr_content_type") == 4 )
    continue;
  else {
    $_product = $_p;
    break;  
  }
}

?>
            
<style>
  #referbox a {
    line-height:32px; margin:20px 0px;display:block;padding-left:32px; background-size:32px 32px;
  }
  
  .home-product-info-bg {
    margin-left:800px;
    width:400px;
    height:100%;
    position:relative;
    background-color: #7A7A7A;
    -moz-opacity: 0.5;
    opacity:.50;
    filter: alpha(opacity=50);  
  }
  .home-product-info {
    top:-350px;
    margin-left:800px;
    width:400px;
    height:100%;
    position:relative;    
    text-align:center;  
  }
  
  .lr-header-frame {
    background-image:url('/media/site/logo-white-jackalope-100.png');
    background-repeat: no-repeat;
    background-position: top center;    
    padding:10px;
    margin:10px 20px;
    text-align:center;
  }
  .lr-header-frame .product-name {
    display:block;
    border-top: 1px solid white;
    border-bottom: 1px solid white;
    font-size:3.5em;
    color:white;
    margin:70px auto 0px auto;
    padding:5px 0px;
  }
  .description {
    color:white;
    padding:5px 15px;
    display:block;
    overflow:hidden;
    height: 2.5em;
    margin-bottom:10px;
  }
  
</style>
<?php $config = Mage::getStoreConfig('shopperslideshow/flexslider', Mage::app()->getStore()->getId()); ?>
<!-- SLIDESHOW -->
<div class="slider">
    <div id="slide-timeline"></div>
    <div id="flexslider" class="flexslider">
        <ul class="slides" id="homeslider">
          
            <?php
      $slides = $this->getSlides();
      foreach($slides as $s) {
            
            $style = $content = '';
            $attr = 'data-img-height="0"';
            if ( !empty($s['image']) ) {
              $imgSize = getimagesize(Mage::getBaseDir('media') .'/'. $s['image']);
              if ($imgSize) {
                $style = "background:url('". Mage::getBaseUrl('media') . $s['image'] . "') 50% 0 no-repeat;";
                $style = "background:url('". $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'banner')->getUrl(). "') 0 0 no-repeat;";
                $attr = 'data-img-height="'.$imgSize[1].'"';
              }
            }
            if ( !empty($s['slide_width']) ) {
              $content = 'style="width:'.$s['slide_width'].'px;"';
            }
            break;
        }
        ?>
        
          <li style="background:url('<?php echo $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'banner')->getUrl();?>') 0 0 no-repeat;" <?php echo $attr; ?> >
                    <div class="home-product-info-bg">
                      
                    </div>
                    <div class="home-product-info">
                      <div class="lr-header-frame">
                        <span class="product-name"><?php echo $label.$_product->getData("name"); ?></span>
                      </div>
                      <div class="description">
                        <?php echo nl2br($_product->getData("short_description")); ?>
                      </div>
                      <button class="button button_white" onclick="document.location='<?php echo $_product->getProductUrl(); ?>'" ><span><span>Learn More</span></span></button>
                      
                    </div>
                    
                </li>
          
          <li>
            <a href="/referralreward/customer/" alt="Invite Friend">
                            <img src="/media/site/invite-friend-slide.png" style="width:1200px;height:350px;border:0px">
            </a>
                          
                     
          </li>
       
        </ul>
    </div>
</div>
<script>
  function do_tweet(){
    var url = "https://twitter.com/intent/tweet?text=";
    url = url+ jQuery("#invitation_message").text();
    window.open(url);
  }
  
  function do_fb(){
     var feed = {
      message:jQuery("#invitation_message").text(),
      link:"http://www.legacyrow.com", 
      caption:"Checkout legacyrow.com!"
    };
  
       var obj = {
          method: 'feed',
          redirect_uri: 'http://www.legacyrow.com',
          link: 'http://www.legacyrow.com',
          picture: 'http://fbrell.com/f8.jpg',
          name: 'Legacy Row',
          caption: 'Checkout Legacy Row',
          description: jQuery("#invitation_message").text()
        };

        function callback(response) {
          console.log (  "Post ID: " + response['post_id']);
        };

        FB.ui(obj, callback);
//   
    // FB.api('/me/feed', 'post', feed, function(response) {
        // if (!response || response.error) {
          // console.log("Error occurred when posting to FB: ", response.error)
        // } else {
          // console.log('Post ID: ' + response.id);
          // //trackEvent("user", "fb-share-ok")
        // }     
        // //$(".ui-dialog").dialog("close")  
        // //$("#fbconfirm").show()
        // //$("#fbmessage").hide()
      // });
   }
</script>

<?php 
/**
          
<?php $config = Mage::getStoreConfig('shopperslideshow/flexslider', Mage::app()->getStore()->getId()); ?>
<!-- SLIDESHOW -->
<div class="slider">
    <div id="slide-timeline"></div>
    <div id="flexslider" class="flexslider">
        <ul class="slides">
			<?php
			$slides = $this->getSlides();
			foreach($slides as $s) {
				$style = $content = '';
				$attr = 'data-img-height="0"';
				if ( !empty($s['image']) ) {
					$imgSize = getimagesize(Mage::getBaseDir('media') .'/'. $s['image']);
					if ($imgSize) {
						$style = "background:url('". Mage::getBaseUrl('media') . $s['image'] . "') 50% 0 no-repeat;";
						$attr = 'data-img-height="'.$imgSize[1].'"';
					}
				}
				if ( !empty($s['slide_width']) ) {
					$content = 'style="width:'.$s['slide_width'].'px;"';
				}
				?>
                <li style="<?php echo $style; ?>" <?php echo $attr; ?> >
					<?php if ( !empty($s['small_image']) ) : ?>
                    <img class="small_image" src="<?php echo Mage::getBaseUrl('media') . $s['small_image'] ?>" alt="" />
					<?php endif; ?>
                    <div class="row text-<?php echo $s['slide_align']; ?>">
                        <div class="content" <?php echo $content; ?>>
							<?php if ( !empty($s['slide_title']) ) : ?>
                            <strong><?php echo $s['slide_title']; ?></strong>
							<?php endif; ?>
							<?php if ( !empty($s['slide_text']) || !empty($s['slide_button']) ) : ?>
                            <div class="border"></div>
							<?php endif; ?>
							<?php if ( !empty($s['slide_text']) ) : ?>
                            <p><?php echo nl2br($s['slide_text']); ?></p>
							<?php endif; ?>
							<?php if ( !empty($s['slide_button']) ) : ?>
                            <button class="button button_white" <?php echo ( empty($s['slide_link']) ? '' : 'onclick="window.location=\''.$s['slide_link'].'\'"' ); ?>><span><span><?php echo $s['slide_button']; ?></span></span></button>
							<?php endif; ?>
                        </div>
                    </div>
                    HAHABAB
                </li>
				<?php
			} // foreach($slides as $s) { ?>
        </ul>
    </div>
</div>
 * 
 * 
 */
?>
<script>
    var CONFIG_SLIDESHOW = {
        animation: "<?php echo ( in_array($config['animation'], array('slide', 'fade')) ? $config['animation'] : 'slide' ); ?>",
        slideshow: <?php echo ( in_array($config['slideshow'], array('true', 'false')) ? $config['slideshow'] : 'true' ); ?>,
        useCSS: false,
        touch: true,
        video: false,
        animationLoop: <?php echo ( in_array($config['animation_loop'], array('true', 'false')) ? $config['animation_loop'] : 'true' ); ?>,
        mousewheel: <?php echo ( in_array($config['mousewheel'], array('true', 'false')) ? $config['mousewheel'] : 'false' ); ?>,
        smoothHeight: <?php echo ( in_array($config['smoothheight'], array('true', 'false')) ? $config['smoothheight'] : 'false' ); ?>,
        slideshowSpeed: <?php echo ( is_numeric($config['slideshow_speed']) ? $config['slideshow_speed'] : 7000 ); ?>,
        animationSpeed: <?php echo ( is_numeric($config['animation_speed']) ? $config['animation_speed'] : 600 ); ?>,
        pauseOnAction: true,
        pauseOnHover: true,
        controlNav: <?php echo ( in_array($config['control_nav'], array('true', 'false')) ? $config['control_nav'] : 'true' ); ?>,
        directionNav: <?php echo ( in_array($config['direction_nav'], array('true', 'false')) ? $config['direction_nav'] : 'true' ); ?>,
        timeline: <?php echo ( in_array($config['timeline'], array('true', 'false')) ? $config['timeline'] : 'true' ); ?>,
        height: "<?php echo (is_numeric($config['height']) ? $config['height'] : 'auto' ); ?>"
    }
</script>
<!-- SLIDESHOW EOF -->