<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */


$session = Mage::getSingleton('adminhtml/session');

if (Mage::getStoreConfig('addinmage_spreadtheword/advanced/expire_notifications')) $exp_notice = (! is_null($session->getExpNotice())) ? $session->getExpNotice() : $this->getExpNotice();
else $exp_notice = false;

?>
<?php if($exp_notice && !empty($exp_notice)) { ?>
	<?php if(isset($exp_notice['soon'])) { ?>
<div class="notification-global notification-global-notice">
	<strong><?php echo $this->helper('spreadtheword')->__('Some coupon codes will expire soon, this will affect Spread The Word extension work.') ?></strong>
		    <?php echo $this->helper('spreadtheword')->__(' Please check <a href="%s">Shopping Card Price Rules</a>.', $this->getShoppingCartPriceRulesUrl());?>
		    <?php echo $this->helper('spreadtheword')->__('See <a onclick="$(\'adm-stw-details-soon\').toggle()" href="javascript:void(0)">Detailed Information</a>.'); ?>
		    <div style="display: none" id="adm-stw-details-soon">
		<br />
		    <?php echo implode('<br/>', $exp_notice['soon'])?>
		     <br /> <strong><?php echo $this->helper('spreadtheword')->__('<br/>Spread The Word will not send expired coupon  codes to your customers.');?></strong> <strong><?php echo $this->helper('spreadtheword')->__('<br/>Please check coupon code configuration before expiration date otheweise all active rules will be desactivated and Spread The Word will be switched in default mode - "Invitation Only".');?></strong>
	</div>
</div>
<?php } ?>
	<?php if(isset($exp_notice['expired'])) { ?>
<div class="notification-global">
	<strong><?php echo $this->helper('spreadtheword')->__('Some Spread The Word rules was desactivated because linked coupon code was expired.') ?></strong>
		    <?php echo $this->helper('spreadtheword')->__(' Please check <a href="%s">Shopping Card Price Rules</a> and <a href="%s">Spread The Word Rules</a>.',$this->getShoppingCartPriceRulesUrl(), $this->getSpreadTheWordRulesUrl());?>
		    <?php echo $this->helper('spreadtheword')->__('See <a onclick="$(\'adm-stw-details-expired\').toggle()" href="javascript:void(0)">Detailed Information.</a>'); ?>
		    <div style="display: none" id="adm-stw-details-expired">
		<br /><?php echo implode('. <br/>', $exp_notice['expired'])?><br />
		<br />
	</div>
</div>
<?php } ?>
<?php } ?>