<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>

<?php $can_show_now_control = $this->testNow(); ?>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td><h3 class="icon-head head-adminhtml-queue-queue"><?php echo Mage::helper('spreadtheword')->__('Invitaion Email Queue') ?></h3></td>
			<td class="a-right">
        <?php if ($can_show_now_control) { ?>
        	<span id="adm_stw_send_now_options"> <span class="adm-stw-adminhtml-queue-control" style="display: none">
						<form id="adm_stw_delay_options">
							<span><?php echo $this->__('Pause between emails') ?> <input type="text" class="input-text" value="" name="stw-delay-value"> <input type="radio" name="stw-delay-dimension" value="sec" checked> <?php echo $this->__('sec') ?> <input type="radio" name="stw-delay-dimension" value="microsec"> <?php echo $this->__('microsec') ?></span>
						</form> <span id="adm-stw-logout-on-finish"><input type="checkbox" value="logout" id="stw-logout" name="stw-logout"><?php echo $this->__('Log out When Done') ?></span>
				</span> <a class="stw-adminhtml-switch-control" id="stw-switch-control" onclick="stwToggleOptions();" href="javascript:void(0)"><?php echo $this->__('see options') ?></a>
			</span>
        <?php } ?>
           <?php echo $this->getButtonsHtml()?>
        </td>
		</tr>
	</table>
</div>
<div>
    <?php echo $this->getGridHtml()?>
</div>
<?php if ($can_show_now_control) { ?>
<script type="text/javascript">
function stwToggleOptions()
{
    $('stw-switch-control').previous().toggle(); 
    ($('stw-switch-control').innerHTML == '<?php echo $this->__('see options') ?>') ? $('stw-switch-control').update('<?php echo $this->__('hide options') ?>') : $('stw-switch-control').update('<?php echo $this->__('see options') ?>');
    if($('adm-stw-logout-on-finish') && !stwTestBrowser()) $('adm-stw-logout-on-finish').remove();
}

function stwSendingAdv()
{
    stwOverlay();
    var options = $('adm_stw_delay_options').serialize();
    $('spreadtheword_queue_grid').insert({top: new Element('iframe', {'src': '<?php echo $this->getUrl('*/*/now') ?>?' + options + '&show_pb=1', 'id':'stw-running-process'})});
	$('stw-running-process').onload = function() {
		stwTimeout();
	};
}
    	
function stwSendingOld()
{
	if($('loading-mask'))$('loading-mask').remove();
	var options = $('adm_stw_delay_options').serialize();
	stwOverlay();
	var stwRequest = new Ajax.Request('<?php echo $this->getUrl('*/*/now') ?>?' + options + '&show_pb=0', {
	method:'get',
	asynchronous: true,
		onCreate: function() {
	   		$('stw-status-container').update().insert({top: new Element('div', {'id': 'stw-progress'})});
	   		$('stw-progress').update('<?php echo $this->__('Sending request for processing messages...') ?>');
		},
		onComplete: function(transport) {
			$('stw-progress').update(transport.responseText);
		},
		onFailure : function() {
	   		$('stw-progress').update('<?php echo $this->__('It is not possible to send emails at the moment.') ?>');
	  	}	  	
	});
}

function stwFinish()
{
	$('stw-running-process').remove();
	setTimeout(function(){$$('#stw-adminhtml-wait, #adm_stw_send_now_button, #adm_stw_send_now_options').invoke('remove')},5000);
	var logout = $F('stw-logout');
	if(logout) window.location = "<?php echo $this->getUrl('adminhtml/index/logout') ?>";
	else setTimeout(function(){window.location = "<?php echo $this->getUrl('*/*/index') ?>";},4000);
}
</script>

<div id="stw-adminhtml-wait" style="display: none">
	<div class="stw-overlay"></div>
	<div id="stw-wait-container">
		<div id="stw-notice-container" style="display: none">
			<p><?php echo $this->__('While updating the status, your server closed the connection according to the request timeout settings.') ?></p>
			<p><?php echo $this->__('You can refresh this page safely. All emails will be sent in the backgroud.') ?></p>
			<p><?php echo $this->__('To ensure correct status bar update, please see how to increase the server request timeout on Add In Mage:: website.') ?></p>
		</div>
		<div id="stw-status-container">
			<div class="stw-progress-bar-container">
				<span id="stw-progress-bar"></span>
			</div>
			<div id="stw-progress"><?php echo $this->__('Preparing data...') ?></div>
			<div id="stw-response-data" style="display: none">
				<span class="stw-data-title"><?php echo $this->__('Status:') ?> </span><span class="stw-right stw-data-value" id="stw-status"></span>
			</div>
			<div id="stw-response-sending" class="stw-data" style="display: none">
				<span class="stw-data-title"><?php echo $this->__('Sending email:') ?> </span><span class="stw-right stw-data-value" id="stw-sending"></span>
			</div>
			<div id="stw-response-failed" class="stw-data" style="display: none">
				<span class="stw-data-title"><?php echo $this->__('Failed') ?> (<span id="stw-failed-qty"></span>) <?php echo $this->__('Latest reason:') ?> </span><span class="stw-right stw-data-value" id="stw-reason"></span>
			</div>
			<div id="stw-response-time" class="stw-data" style="display: none">
				<div class="stw-left">
					<span class="stw-data-title"><?php echo $this->__('Elapsed time:') ?> </span><span class="stw-data-value" id="stw-elapsed"></span>
				</div>
				<div id="stw-estimated-time" class="stw-right" style="display: none">
					<span class="stw-data-title"><?php echo $this->__('Estimated time left:') ?> </span><span class="stw-data-value" id="stw-estimated"></span>
				</div>
			</div>
		</div>
	</div>
</div>
<?php } ?>