<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>

<div class="reassign_discount_container">
	<form name="reassign_discounts" id="reassign_discounts" method="post" action="<?php echo $this->getActionUrl() ?>">
		<table cellspacing="0">
			<tr>
				<td><strong><?php echo $this->__('Reassign all failed discounts')?></strong>
			<?php echo $this->__('with the amount:')?><span class="required">*</span><?php echo $this->getFailedDiscountsSelectHtml(); ?>
			<?php echo $this->__('change them to:')?><span class="required">*</span><?php echo $this->getNewDiscountsSelectHtml(); ?>
			<?php if($this->haveAccess()) { ?>
				<?php echo $this->__('or')?>
				<a href="<?php echo $this->getShoppingCartPriceRulesUrl() ?>" target="_blank"><b><?php echo $this->__('create a new coupon code')?></b></a>
			<?php } ?>
		</td>
				<td class="a-right"><?php echo $this->getReassignButtonHtml(); ?></td>
			</tr>
		</table>
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
	</form>
</div>
<script type="text/javascript">
    var reassignForm = new varienForm('reassign_discounts',true);
    var reassignFormValidate = new Validation('reassign_discounts',{immediate : true,onElementValidate:stwValidateElements});

 	function stwValidateElements(selected,el){
  	   if(selected) el.removeClassName('required');
	   else el.addClassName('required').next().remove();
    }
</script>