<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>

<div class="switcher" id="stw_store_switcher">
	<label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label> <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
    <?php foreach ($this->getStoreSelectOptions() as $_value=>$_option): ?>
    <?php if (isset($_option['is_group'])): ?>
        <?php if ($_option['is_close']): ?>
            </optgroup>
        <?php else: ?>
            <optgroup label="<?php echo $_option['label'] ?>" style="<?php echo $_option['style'] ?>">
        <?php endif; ?>
        <?php continue?>
    <?php endif; ?>
      <option value="<?php echo $_value ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected']?'selected="selected"':'' ?> style="<?php echo $_option['style'] ?>">
          <?php echo $_option['label']?>
      </option>
    <?php endforeach ?>
    
	
	</select>
    <?php if($this->canShow()) { ?>
    	<form action="<?php echo $this->getSaveUrl() ?>" method="get">
		<input class="stw-switch" id="use" type="checkbox" onclick="stwSwitchValues(this)" /> <label for="use" class="inherit" title="<?php echo $this->getLabel() ?>"><?php echo $this->getLabel() ?></label>
		<button style="display: none" id="save-stw-switch-data" type="submit" class="scalable save stw-switch">
			<span><?php echo $this->__('Save Config') ?></span>
		</button>
	</form>
	<script type="text/javascript">
		//<![CDATA[

		function stwSwitchValues(element) {

		    if (element.checked) {
				$('store_switcher').disable();     
				$('save-stw-switch-data').show();   
		    }
		    else {
				$('store_switcher').removeAttribute('disabled');
				$('save-stw-switch-data').hide();          
		    }
		}

		//]]>
		</script>
    <?php } ?>
</div>
