<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

$max_recipients = $this->helper('spreadtheword')->getMaxRecipients();
$max_chars = $this->helper('spreadtheword')->getMaxChars();

?>

<div id="manual-view" class="service-specific" style="display: none">
	<script type="text/javascript">

i=1;
var recipCount  = 1;
var maxRecip    = <?php echo $max_recipients ?>;
  	
function stwRemoveRecipient(i)
{
	$('recipients_name_'+i).up(1).remove();
	recipCount--;
	if(recipCount<maxRecip && maxRecip != 0) {
		$('add_recipient_button').show();
		$('max_recipient_message').hide();
	}
	return false;
}
	
function stwAddRecipient()
{
	ul = $('recipients_options');
	var li_mail = Element.extend(document.createElement("LI"));
	li_mail.addClassName('fields additional-row');
	li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->__('Remove Email') ?>" onclick="stwRemoveRecipient('+i+'); return false" class="btn-remove"><?php echo $this->__('Remove Email') ?>"<\/a><\/p>'
	li_mail.innerHTML += '<div class="field"><label for="recipients_name_'+i+'" class="required"><em>*<\/em><?php echo $this->__('Full Name:') ?><\/label><input name="recipients['+i+'][name]" type="text" class="input-text required-entry" id="recipients_name_'+i+'" /><\/div>';
	li_mail.innerHTML += '<div class="field"><label for="recipients_email_'+i+'" class="required"><em>*<\/em><?php echo $this->__('Email Address:') ?><\/label><input name="recipients['+i+'][email]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email_'+i+'" type="text" class="input-text required-entry validate-email" /><\/div>';
	i++;
	recipCount++;
	if(recipCount>=maxRecip && maxRecip != 0) {
		$('add_recipient_button').hide();
		$('max_recipient_message').show();
	}
	ul.appendChild(li_mail);
}

function stwLoadManualView(key)
{
	var manual_container = $('manual-invitations');		
	if(!manual_container){
		load_manual = Element.extend(document.createElement("div"));
		load_manual.addClassName('adm-stw-absolute adm-stw-loading-small');
		$('service-box').appendChild(load_manual);
		stwLoadManualBody(key);			
	}
	else stwProcessManualView();			
}

Ajax.Responders.register({
	onComplete: function() {
		if(Ajax.activeRequestCount == 0){
			stwProcessManualView();
			load_manual.remove();
			stwManualMessage();
			<?php if ($max_chars) echo "stwCountChars('adm-stw-personal-message',".$max_chars.");"?>
		}
	}
});

function stwLoadManualBody(key){
	new Ajax.Request('<?php echo Mage::getUrl("spreadtheword/manual/body") ?>', {
		parameters: 'form_key='+key,
		onComplete: function(body_transport) {
			stwLoadManualTitle(body_transport);
			},
		on307: function(){
			location.href = '<?php echo Mage::getUrl("spreadtheword") ?>';
		}		
	}); 
}

function stwLoadManualTitle(body_transport)
{
	new Ajax.Request('<?php echo Mage::getUrl("spreadtheword/manual/title") ?>', {
		onComplete: function(title_transport) {
			$('adm-stw-top-manual-container').update(title_transport.responseText);
			$('manual-view').update(body_transport.responseText);
		}	
	}); 
}

var manualForm = new VarienForm('manual-invite');
manualForm.submit = function() {
	if(this.validator.validate()) {
		this.form.submit();
	}
}.bind(manualForm);

function stwManualMessage() 
{
	$('adm-stw-add-message').observe("click", function(){
		$$('#adm-stw-remove-message, #adm-stw-sh-message, #counter-adm-stw-message, #custom-message').invoke('show');
		$('adm-stw-add-message').hide();
		$('adm-stw-personal-message').show().focus();
	});

	$('adm-stw-sh-message').observe("click", function(){
		$$('#custom-message, #adm-stw-sh-message').invoke('hide');
		$('adm-stw-oe-message').show();
	});

	$('adm-stw-oe-message').observe("click", function(){
		$$('#custom-message, #adm-stw-sh-message').invoke('show');
		$('adm-stw-oe-message').hide();
	});

	$('adm-stw-remove-message').observe("click", function(){
		$('adm-stw-personal-message').clear().hide();
		$$('#adm-stw-custom-message, #adm-stw-sh-message, #adm-stw-oe-message, #counter-adm-stw-message, #adm-stw-remove-message').invoke('hide');
		$$('#adm-stw-add-message').invoke('show');
		<?php if ($max_chars) echo "$('counter-adm-stw-personal-message').update('".$max_chars."/".$max_chars."').addClassName('adm-stw-chars-limit-ok')"?>
	});
}	
</script>
</div>
