<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

?>
<div class="entry-edit custom-options rule-<?php echo $this->_rule; ?>-custom-options">
	<div class="entry-edit-head">
    <?php $title = ($this->_rule == 'sender') ? $this->__('Service Rule Exceptions for Senders') : $this->__('Service Rule Exceptions for Friends'); ?>
        <h4><?php echo $title; ?></h4>
		<div class="right"><?php echo $this->getAddButtonHtml() ?></div>
	</div>

	<div id="rule_<?php echo $this->_rule; ?>_options_container" class="box">
		<div id="rule_<?php echo $this->_rule; ?>_options_container_top"></div>
        <?php echo $this->getOptionsBoxHtml()?>
    </div>
</div>
<script type="text/javascript">
varienWindowOnload(true);
</script>
