<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();

$helper = $this->helper('shoppersettings/image');
list($defaultImgX, $defaultImgY) = $helper->getDefaultSize();
list($imgX, $imgY) = $helper->getMainSize();
if ( $imgX > 300 ) {
    $imgX = 300;
    $imgY = $helper->calculateHeight($imgX);
}

$product_img_box_width = $defaultImgX;
if ( $defaultImgX != $imgX ) {
    $product_img_box_width = $imgX;
}
//add image border
$product_img_box_width += 18;
?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-img-box" style="width:<?php echo $product_img_box_width; ?>px">
                <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>

                <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
                <p class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($imgX, $imgY); ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($imgX*2, $imgY*2); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" width="<?php echo $imgX;?>" height="<?php echo $imgY;?>" />
                </p>
                <?php else: ?>
                <p class="product-image">
                    <?php
                    $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgX, $imgY).'" data-srcX2="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgX*2, $imgY*2).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" width="'.$imgX.'" height="'.$imgY.'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </p>
                <?php endif; ?>

            </div>

            <div class="product-shop">
                <div class="product-shop-info">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>

                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('other');?>

                    <?php if(!$_product->isGrouped()): ?>
                    <div class="qty-container clearfix">
                        <label for="qty"><?php echo $this->__('Qty') ?>:</label>
                        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                    </div>
                    <?php endif; ?>

                    <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                    <?php endif; ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif;?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('addto') ?>
                    <div class="clear"></div>
                    <?php echo $this->getChildHtml('shopper_product_addthis') ?>
                </div>
            </div>
            <div class="clearer"></div>
        </form>
        <script type="text/javascript">
            //<![CDATA[

            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function (button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;
                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    // Start of our new ajax code
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    url = url.replace("checkout/cart", "ajax/index"); // New Code
                    var data = jQuery('#product_addtocart_form').serialize();
                    data += '&isAjax=1';
                    jQuery('#ajax_loader').css('display', 'block');
                    try {
                        jQuery.ajax({
                            url:url,
                            dataType:'jsonp',
                            type:'post',
                            data:data,
                            success:function (data) {
                                jQuery('#ajax_loader').css('display', 'none');
                                parent.setAjaxData(data, true);

                                jQuery('body').append('<div class="alert"></div>');
                                jQuery('.alert').slideDown(400);
                                jQuery('.alert').html(data.message).append('<button></button>');
                                jQuery('button').click(function () {
                                    jQuery('.alert').slideUp(400);
                                });
                                jQuery('.alert').slideDown('400', function () {
                                    setTimeout(function () {
                                        jQuery('.alert').slideUp('400', function () {
                                            jQuery(this).slideUp(400)
                                        });
                                    }, 7000)
                                });
                            }
                        });
                    } catch (e) {
                    }
                    // End of our new ajax code
                    this.form.action = oldUrl;

                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);

            //]]>
        </script>

    </div>
</div>