<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */


$max_recipients = $this->helper('spreadtheword')->getMaxRecipients();
$max_chars = $this->helper('spreadtheword')->getMaxChars();

?>

<div id="manual-invitations">
	<form method="post" action="<?php echo $this->getUrl('*/manual/invite') ?>" class="form-list" id="manual-invite">
		<div class="top-left"><?php echo $this->__('Sender Information:') ?></div>
		<div class="top-right">
			<button id="find-friends" onClick="stwProcessData('manual-invite')" title="<?php echo $this->__('Send Invitations') ?>" type="submit">
				<span><span><?php echo $this->__('Send Invitations') ?></span></span>
			</button>
		</div>
		<div class="view-container">
			<div class="separator"></div>
			<ul class="form-list">
			<?php if (! Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
        	<li class="fields">
					<div class="field">
						<label for="sender_name" class="required"><em>*</em><?php echo $this->__('Your Name') ?>:</label> <input name="sender_name" type="text" title="<?php echo $this->__('Your Name') ?>" class="input-text required-entry" id="sender_name" />
					</div>
					<div class="field">
						<label for="sender_email" class="required"><em>*</em><?php echo $this->__('Your Email Address') ?>:</label> <input name="sender_email" value="" title="<?php echo $this->__('Your Email Address') ?>" id="sender_email" type="text" class="input-text required-entry validate-email" />
					</div>
				</li>
        	<?php } else { ?>
        	<li class="fields">
					<div class="field">
						<label for="sender_name"><?php echo $this->__('Your Name:') ?></label> <span class="sender-data"><?php echo Mage::getSingleton('customer/session')->getCustomer()->getName(); ?></span>
					</div>
					<div class="field">
						<label for="sender_email"><?php echo $this->__('Your Email Address:') ?></label> <span class="sender-data"><?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail(); ?></span>
					</div>
				</li>
			<?php } ?>
        	</ul>
			<div class="separator"></div>
		</div>
		<div class="top-left"><?php echo $this->__('Recipients Information:') ?></div>
		<div class="top-right">
			<div id="max_recipient_message" style="display: none;">
			<?php if ($max_recipients): ?>
				<p class="limit"><?php echo $this->__('Only %d recipients allowed.', $max_recipients) ?></p>
			<?php endif; ?>
			</div>
			<?php if (1 < $max_recipients): ?>
			<button onclick="stwAddRecipient();" id="add_recipient_button" title="<?php echo $this->__('Add Recipient') ?>" type="button">
				<span><span><?php echo $this->__('Add Recipient') ?></span></span>
			</button>
			<?php endif; ?>
		</div>
		<div class="view-container">
			<div class="separator"></div>
			<ul class="form-list" id="recipients_options">
				<li class="fields">
					<div class="field">
						<label for="recipients_name_0" class="required"><em>*</em><?php echo $this->__('Full Name:') ?></label> <input name="recipients[0][name]" type="text" class="input-text required-entry" id="recipients_name_0" />
					</div>
					<div class="field">
						<label for="recipients_email_0" class="required"><em>*</em><?php echo $this->__('Email Address:') ?></label> <input name="recipients[0][email]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email_0" type="text" class="input-text required-entry validate-email" />
					</div>
				</li>
			</ul>
		</div>

		<div class="separator"></div>
		<div class="adm-stw-message-control adm-stw-control-left">
			<span class="control-left"><?php echo $this->__('Personal message') ?></span> <span class="control-right"> <a href="javascript:void(0)" id="adm-stw-add-message"><?php echo $this->__('add a personal message') ?></a> <a style="display: none" href="javascript:void(0)" class="adm-stw-remove" id="adm-stw-remove-message"><?php echo $this->__('remove message') ?></a>
			</span> <span class="control-right"> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-sh-message" style="display: none;"><?php echo $this->__('save & hide') ?></a> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-oe-message" style="display: none;"><?php echo $this->__('open & edit') ?></a>
			</span>
			<?php if ($max_chars) { ?>
			<span class="control-right" id="counter-adm-stw-message" style="display: none;">
				<?php echo $this->__('characters left:') ?> <span id="counter-adm-stw-personal-message" class="adm-stw-chars-limit-ok"><?php echo $max_chars ?></span>
			</span>
		<?php } ?>
		</div>
		<div id="custom-message" style="display: none">
			<textarea id="adm-stw-personal-message" rows="3" name="personal-message"></textarea>
		</div>
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
	</form>
</div>