<?php
    $link   = $this->getUrl('invite/'.$this->getItem()->getUrl());
    $title  = $this->__('This is a personal registration link to the site');
?>

<style>
  .share-links li {
     padding:3px;
  }
</style>
<ul class="share-links" style="float:left;margin-top:10px;width:250px">
    <li><a class="icosoc facebook"      title="<?php echo $this->__('Share in') ?> Facebook"    target="_blank" rel="nofollow"
            href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $link ?>">
        </a>
    </li>
    <li><a class="icosoc twitter"       title="<?php echo $this->__('Share in') ?> Twitter"     target="_blank" rel="nofollow"
            href="http://twitter.com/share?url=<?php echo $link ?>&text=<?php echo $title ?>">
        </a>
    </li>
    <li><a class="icosoc pinterest"     title="<?php echo $this->__('Share in') ?> Pinterest"   target="_blank" rel="nofollow"
            href="http://pinterest.com/pin/create/button/?url=<?php echo $link ?>">
        </a>
    </li>
    <li><a class="icosoc linkedin"      title="<?php echo $this->__('Share in') ?> LinkedIn"    target="_blank" rel="nofollow"
            href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo $link ?>&title=<?php echo $title ?>&summary=">
        </a>
    </li>
    <li><a class="icosoc myspace"		title="<?php echo $this->__('Share in') ?> MySpace"		target="_blank" rel="nofollow"
            href="http://www.myspace.com/Modules/PostTo/Pages/?u=<?php echo $link ?>&t=<?php echo $title ?>">
        </a>
    </li>
  
    
    <li><a class="icosoc livejournal"	title="<?php echo $this->__('Share in') ?> LiveJournal"	target="_blank" rel="nofollow"
            href="http://www.livejournal.com/update.bml?event=<br /><br /><a href='<?php echo $link ?>' target='_blank' rel='nofollow'><?php echo $title ?></a>">
        </a>
    </li>
    <li><a class="icosoc delicious"		title="<?php echo $this->__('Share in') ?> Delicious"	target="_blank" rel="nofollow"
            href="http://delicious.com/save?url=<?php echo $link ?>&title=<?php echo $title ?>">
        </a>
    </li>
    <li><a class="icosoc stumbleupon"	title="<?php echo $this->__('Share in') ?> Stumbleupon"	target="_blank" rel="nofollow"
            href="http://www.stumbleupon.com/submit?url=<?php echo $link ?>&title=<?php echo $title ?>">
        </a>
    </li>
    <li><a class="icosoc reddit"		title="<?php echo $this->__('Share in') ?> Reddit"	target="_blank" rel="nofollow"
            href="http://www.reddit.com/submit?url=<?php echo $link ?>&title=<?php echo $title ?>">
        </a>
    </li>
        
         <li><div>
            <div class="g-plusone" data-annotation="none" data-href="<?php echo $link ?>"></div>
            <script type="text/javascript">
              (function() {
                var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                po.src = 'https://apis.google.com/js/plusone.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
              })();
            </script>
        </div>
    </li>
</ul>
