<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

/**	$this->getActionSubTitle()
 *	Получение текста действия в зависимости от текущего режима правила приглашения
 * 	@return string
 **/


$show_manual = $this->canShowManualInvitation();
?>

<div id="adm-stw-top-container" style="padding-top: 80px"></div>
<?php if($show_manual) {?>
<div style="display: none; margin-top: 10px; height: 70px; font-size: 20px;" id="adm-stw-top-manual-container"></div>
<?php } ?>
<div class="description" id="block-description">
	<h1><?php echo $this->__('Invite your friends') ?></h1>
	<h2><?php echo $this->getActionSubTitle(); ?></h2>
	<?php foreach ($this->getDescriptionText() as $line ) : ?>
	<p><?php echo $line ?></p>
	<?php endforeach; ?>
</div>