<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */


$action = $this->getRequest()->getControllerName();

?>

<div class="steps">
	<div class="first round">
		<strong id="first-step" <?php if($action == 'index') echo 'class="active-step"'; ?>></strong> <b> <em><?php echo $this->__('Take your contacts') ?></em> <span><?php echo $this->__('Choose where to take your friend list from.') ?><?php if($action !== 'index') : ?> <a href="<?php echo Mage::getUrl('spreadtheword')?>"><?php echo $this->__('Start over.') ?></a><?php endif; ?></span>
		</b>
	</div>
	<div class="second round">
		<strong id="second-step" <?php if($action == 'friends') echo 'class="active-step"'; ?>></strong> <b> <em><?php echo $this->__('Select recipients') ?></em> <span><?php echo $this->__('Select people you want to invite from the list.'); ?></span>
		</b>
	</div>
	<div class="third round">
		<strong id="third-step" <?php if($action == 'success') echo 'class="active-step"'; ?>></strong> <b> <em><?php echo $this->__('Send invitations') ?></em> <span><?php echo $this->getThirdStepText(); ?></span>
		</b>
	</div>
</div>
