<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */


$alpha_index = $this->getAlphaIndex();
$mark_customers = $this->markCustomers();
$mark_invited = $this->markInvited();
$show_picture = $this->showPicture();
$max_chars = $this->helper('spreadtheword')->getMaxChars();
$max_chars_direct = $this->helper('spreadtheword')->getDirectMaxChars();
$curent_service_data = $this->getCurrentService();
$length = null;
if ($curent_service_data ['code'] == 'twitter') $length = ($this->isDiscountMode()) ? 141 : 125;
$twitter_limit = ($length) ? "stwCountChars('adm-stw-personal-message',{$length});" : null;

?>

<?php $friends_count = 0; $i= 0; ?>
<div class="adm-stw-friends">
	<div id="alphaindex">
		<ol type="desc">
		<?php foreach ($alpha_index as $letter => $friends){ ?>
		<?php $friends_count += count($friends); ?>
			<li><a class="adm-stw-letters<?php if($i == 0) : ?> current-letter<?php endif; ?>" id="adm-stw-letters" href="javascript:void(0)" onclick="stwScrollFriends('<?php echo $letter ?>',null,null,this)"><?php echo $letter ?></a></li>
		<?php $i++; } ?>
		</ol>
	</div>
	<form id="adm-stw-friends-book" action="<?php echo $this->getUrl('*/send') ?>" method="post">
		<div class="adm-stw-ab">
			<div class="adm-stw-control-left">
				<span class="control-left"><?php echo $this->__('Friend List'); ?></span> <span class="control-right"> <label for="check-all"><?php echo $this->__('select all'); ?></label> <input type="checkbox" id="check-all" value="0" name="check-all">
				</span> <span class="control-right"><?php echo $this->__('selected'); ?> 
					<span id="adm-stw-control-selected">0</span> <?php echo $this->__('of'); ?> 
					<span><?php echo $friends_count; ?></span> </span>
			</div>
			<div class="adm-stw-absolute adm-stw-loading-big" id="adm-stw-loading"></div>
			<div class="adm-stw-absolute adm-stw-letter round" id="adm-stw-letter" style="display: none"></div>
			<div id="friends" class="friends">
				<div class="adm-stw-absolute adm-stw-letter round" id="adm-stw-letter" style="display: none"></div>
				<ol class="friends-container" id="friends-container" style="display: none">
				<?php $i = 0; ?>
				<?php foreach ($alpha_index as $letter => $friends){ ?>
					<li id="<?php echo $letter ?>">
						<h2><?php echo $letter ?></h2>
						<ul>		
						<?php foreach ($friends as $friend){ $i++?>
							<li class="alpha-container">
							<?php if($show_picture) { ?>
								<div class="friends-picture">
								<?php if(isset($friend['friend_picture'])) { ?>
									<img src="<?php echo $friend['friend_picture']?>" />
								<?php } else { ?>
									<span class="adm-stw-nopicture"></span>
								<?php } ?>
								</div>
							<?php } ?>
							<div class="adm-stw-select">
									<input type="checkbox" id="<?php echo $i; ?>" class="friend" value="<?php echo $friend['friend_invite_link'] ?>" name="friends[<?php echo $i; ?>]">
								</div>

								<div class="friend-info">
							<?php if(isset($friend['already_customer']) && $mark_customers) { ?>
								<div class="friend-row">
										<span class="adm-stw-customer"><?php echo $this->__('existing customer'); ?></span>
									</div>
							<?php } ?>
							<?php if(isset($friend['invited']) && $mark_invited) { ?>
								<div class="friend-row">
										<span class="adm-stw-invited"><?php echo $this->__('invited before'); ?></span>
									</div>
							<?php } ?>
							</div>
								<div class="friend-data">
									<div class="friend-row">
										<span class="adm-stw-name"><?php echo $friend['friend_name']?></span>
									</div>
								<?php if($friend['source_type'] !== 'file' && isset($friend['friend_url'])) { ?>
								<div class="friend-row">
										<span class="adm-stw-profile"> <a target="_blank" href="<?php echo $friend['friend_url']?>"><?php echo $this->__('View Profile'); ?></a></span>
									</div>
								<?php } ?>
								<?php if($friend['source_type'] !== 'social' && isset($friend['friend_id'])) { ?>
								<div class="friend-row">
										<span class="adm-stw-profile-email adm-stw-profile"><?php echo $friend['friend_id']?></span>
									</div>
								<?php } ?>
							</div>
							</li>
					<?php } ?>
					</ul>
					</li>
			<?php } ?>
			</ol>
			</div>
			<div id="track1"><div id="handle1" class="selected" style="top: 0px; position: relative;"></div></div>
		<?php if($curent_service_data['type'] !== 'social') { ?>
		<div id="adm-stw-custom-message" class="adm-stw-message-container" style="display: none">
				<div class="adm-stw-textarea-container">
					<textarea id="adm-stw-personal-message" rows="3" name="personal-message"></textarea>
				</div>
				<div class="adm-stw-message-control adm-stw-control-left">
					<span class="control-left"><?php echo $this->__('Personal message'); ?></span> <span class="control-right"> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-sh-message"><?php echo $this->__('save & hide'); ?></a> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-oe-message" style="display: none"><?php echo $this->__('open & edit'); ?></a>
					</span>
					<?php if ($max_chars) { ?>
					<span class="control-right">
					<?php echo $this->__('characters left:'); ?> <span id="counter-adm-stw-personal-message" class="adm-stw-chars-limit-ok"><?php echo $max_chars ?></span>
					</span>
				<?php } ?>
			</div>
			</div>
		<?php } elseif ($curent_service_data['type'] == 'social') { ?>
		<div id="adm-stw-custom-message" class="adm-stw-message-container" style="display: none">
				<div class="adm-stw-textarea-container">
					<textarea id="adm-stw-personal-message" class="adm-stw-personal-message" disabled="disabled" rows="4" name="personal-message"><?php echo $this->getDirectTemplate(); ?></textarea>
				</div>
				<div class="adm-stw-message-control adm-stw-control-left adm-stw-direct-options">
					<span class="control-left"><?php echo $this->__('Personal message'); ?></span> <span> <input type="radio" id="adm-stw-direct-template" name="stw-direct-message" value="template" checked> <span class="adm-stw-direct-template"><?php echo $this->__('use template') ?></span> <input type="radio" id="adm-stw-direct-custom" name="stw-direct-message" value="custom"> <span
						class="adm-stw-direct-custom"><?php echo $this->__('customize') ?></span>
					</span> <span id="adm-stw-dm-control" style="display: none"> <span class="control-right"> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-sh-message"><?php echo $this->__('save & hide'); ?></a> <a href="javascript:void(0)" class="adm-stw-msg" id="adm-stw-oe-message" style="display: none"><?php echo $this->__('open & edit'); ?></a>
					</span>
					<?php if ($max_chars_direct) { ?>
					<span class="control-right">
						<?php echo $this->__('characters left:'); ?> <span id="counter-adm-stw-personal-message" class="adm-stw-chars-limit-ok"><?php echo $max_chars_direct ?></span>
					</span>
					<?php } ?>
				</span>
				</div>
			</div>
		<?php } ?>
	</div>

		<div id="adm-stw-people">
			<div class="adm-stw-control-right">
				<span class="control-left"><?php echo $this->__('Selected Friends'); ?></span> <span class="control-right"> <a id="remove-all" class="adm-stw-remove" href="javascript:void(0)"><?php echo $this->__('remove all'); ?></a>
				</span>
			</div>
			<ul id="adm-stw-selected-friends"></ul>
			<div id="track2"><div id="handle2" class="selected" style="top: 0px; position: relative;"></div></div>
		<?php if($curent_service_data['type'] !== 'social') { ?>
		<div class="adm-stw-message adm-stw-control-right">
				<a href="javascript:void(0)" id="adm-stw-add-message"><?php echo $this->__('add a personal message'); ?></a> <a style="display: none" href="javascript:void(0)" class="adm-stw-remove" id="adm-stw-remove-message"><?php echo $this->__('remove message'); ?></a>
			</div>
		<?php } elseif($curent_service_data['type'] == 'social') { ?>
		<div class="adm-stw-message adm-stw-control-right">
				<a href="javascript:void(0)" id="adm-stw-see-message"><?php echo $this->__('see my personal message'); ?></a>
			</div>
		<?php } ?>
	</div>
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
	</form>
</div>

<script type="text/javascript">
var ul_selected = $('adm-stw-selected-friends');
var checkboxes = $$("#friends input[type=checkbox]");
var cbControl = $("check-all");
var remove_all = $("remove-all");
var adm_stw_s;
var total_friends = <?php echo $friends_count ?>;

<?php if($curent_service_data['type'] !== 'social') { ?>
$('adm-stw-add-message').observe("click", function(){
	 $$('#adm-stw-custom-message,#adm-stw-remove-message').invoke('show');
	 $('adm-stw-personal-message').focus();
	 $('adm-stw-add-message').hide();
});
$('adm-stw-remove-message').observe("click", function(){
	 $('adm-stw-personal-message').clear();
	 $$('#adm-stw-custom-message, #adm-stw-oe-message, #adm-stw-remove-message').invoke('hide');
	 $$('#adm-stw-personal-message, #adm-stw-sh-message, #adm-stw-add-message').invoke('show');
	 <?php if ($max_chars) echo "$('counter-adm-stw-personal-message').update('".$max_chars."/".$max_chars."').addClassName('adm-stw-chars-limit-ok')"?>
});
$('adm-stw-sh-message').observe("click", function(){
	 $$('#adm-stw-personal-message, #adm-stw-sh-message').invoke('hide');
	 $('adm-stw-oe-message').show();
});
$('adm-stw-oe-message').observe("click", function(){
    $$('#adm-stw-personal-message, #adm-stw-sh-message').invoke('show');
	$('adm-stw-oe-message').hide();
});
function stwSendInv(){
    var selected_frds = $$("#adm-stw-selected-friends li").length;
    if(selected_frds <= 0) alert("<?php echo $this->__('Please select the friends you want to invite.'); ?>");
    else $('adm-stw-friends-book').submit();
}
<?php } elseif($curent_service_data['type'] == 'social') { ?>
function stwSendInv(){
    <?php if($this->isDiscountMode()) { ?>
    Validation.add('adm-stw-personal-message', '<?php echo $this->__('{{var store}}, {{var amount}}, {{var code}} and {{var page}} tags are required. Do not modify or remove them.'); ?>', function (v) {
    	return /(?:{{var store}})/.test(v) && /(?:{{var amount}})/.test(v) && /(?:{{var code}})/.test(v) && /(?:{{var page}})/.test(v);
    });
    <?php } else { ?>
    Validation.add('adm-stw-personal-message', '<?php echo $this->__('{{var store}} and {{var page}} tags are required. Do not modify or remove them.'); ?>', function (v) {
    	return /(?:{{var store}})/.test(v) && /(?:{{var page}})/.test(v);
    });
    <?php } ?>
    var valid = new Validation('adm-stw-friends-book');
    var result = valid.validate();
    var selected_frds = $$("#adm-stw-selected-friends li").length;
    if(selected_frds <= 0) alert("<?php echo $this->__('Please select the friends you want to invite.'); ?>");
    if(result && selected_frds > 0) $('adm-stw-friends-book').submit();
}

$('adm-stw-see-message').observe("click", function(){
    ($('adm-stw-see-message').innerHTML == '<?php echo $this->__('see my personal message') ?>') ? $('adm-stw-see-message').update('<?php echo $this->__('hide personal message') ?>') : $('adm-stw-see-message').update('<?php echo $this->__('see my personal message') ?>');
	$('adm-stw-custom-message').toggle();
});

$$('#adm-stw-direct-template, #adm-stw-direct-custom').each(function(dm_options) {
    dm_options.observe('click', function(ev) {
	    stwHandleOoptions();
	});
});

function stwHandleOoptions() 
{
    var dm_type = $$('input:checked[type="radio"][name="stw-direct-message"]').pluck('value');
    if(dm_type == 'custom') {
			$('adm-stw-personal-message').enable().focus();
			$('adm-stw-dm-control').show();
			<?php echo $twitter_limit; ?>
    } 
    else {
	    var template = "<?php echo str_replace("\r", "\\n\\", trim($this->getDirectTemplate())); ?>";
	    $('adm-stw-personal-message').disable().value = template;
	    $('adm-stw-dm-control').hide();
	    <?php if ($max_chars_direct) echo "stwCountChars('adm-stw-personal-message',".$max_chars_direct.");"?>
    }
}

$('adm-stw-sh-message').observe("click", function(){
	 $$('#adm-stw-personal-message, #adm-stw-sh-message').invoke('hide');
	 $('adm-stw-oe-message').show();
});

$('adm-stw-oe-message').observe("click", function(){
	$$('#adm-stw-personal-message, #adm-stw-sh-message').invoke('show');
	$('adm-stw-oe-message').hide();
});
<?php } ?>

$$('a.adm-stw-letters').each(function(letter) {
    letter.observe('mouseover', function(ev) {
	    stwShowLetter(ev.target.innerHTML);
	});
});

$('alphaindex').observe('mouseout', function() {
    $('adm-stw-letter').hide();
});

remove_all.observe("click", function(){
    ul_selected.update();
    cbControl.checked = false;
    stwCheckControlElms();
    checkboxes.each(function(fr){
		fr.checked = false;
		stwUnselect(fr);
    });  
    stwCheckControlElms();
});

cbControl.observe("click", function(){
    if(cbControl.checked) {
        adm_stw_s = true; 
        ul_selected.update();
	}
    else adm_stw_s = false;
    checkboxes.each(function(fr){
	fr.checked = cbControl.checked;
        if(adm_stw_s) stwSelect(fr);
        else {
            ul_selected.update();
            stwUnselect(fr);
        };
    });
    stwCheckControlElms();
});

var friends = $$("#adm-stw-friends-book input[type=checkbox].friend");
friends.each(function(fr){
    fr.observe("click", function(){
		if(fr.checked) stwSelect(fr);
		else {
		    cbControl.checked = false;
			$$('li[name='+fr.readAttribute('id')+']').invoke('remove');
			stwUnselect(fr);
		}
		stwCheckControlElms();
	});
    
});

$('adm-stw-selected-friends').observe('click', function(e, el) {
    if (el = e.findElement('li')) {
	    fr = $(el.readAttribute('name'));
	    fr.checked = false;
	    cbControl.checked = false;
      	el.remove();
      	stwUnselect(fr);
    }
});
var slider1 = new Control.Slider('handle1', 'track1', {
	axis: 'vertical',
	onSlide: function(v) { stwScrollVertical(v, $('friends'), slider1); },
	onChange: function(v) { stwScrollVertical(v, $('friends'), slider1); $$('.adm-stw-letters').invoke('removeClassName','current-letter'); }
}); 
var slider2 = new Control.Slider('handle2', 'track2', {
	axis: 'vertical',
	onSlide: function(v) { stwScrollVertical(v, $('adm-stw-selected-friends'), slider2); },
	onChange: function(v) { stwScrollVertical(v, $('adm-stw-selected-friends'), slider2); }
});

document.observe('dom:loaded', function(){
    <?php if($this->selectAll()) echo 'cbControl.click();'; ?>
    <?php if($max_chars_direct && $curent_service_data['type'] == 'social' && $curent_service_data['code'] !== 'twitter') echo "stwCountChars('adm-stw-personal-message',{$max_chars_direct});"?>
    <?php if($max_chars && $curent_service_data['type'] !== 'social' && $curent_service_data['code'] !== 'twitter') echo "stwCountChars('adm-stw-personal-message',{$max_chars});"?>
    <?php echo $twitter_limit; ?>
    $('adm-stw-loading').remove();
    $('friends-container').show();
    stwCheckControlElms();
});
</script>