<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

$style = $this->getDateStyle();
$id = $this->getFieldId();
$image = $this->getSkinUrl('images/grid-cal.gif');
$name = $this->getFieldName();
$target = $this->_rule;
?>
<script type="text/javascript">
//<![CDATA[
<?php echo $target; ?>OptionTemplateDynamicLevels = 
   '<table class="border rule-data" cellpadding="0" cellspacing="0">'+
   		'<tr class="headings">'+
			'<td id="rule-settings" class="prev"><span class="rule-settings"><?php echo $this->__('From Date') ?></span><span><input style="width: 50px !important;" class="input-text rule-date" type="text" id="<?php echo $id ?>_{{option_id}}_from_date" name="<?php echo $name ?>[{{option_id}}][from_date]"  value="{{from_date}}"><img id="<?php echo $id ?>_{{option_id}}_from_date_trig" title="<?php echo $this->__('Date selector') ?>" class="v-middle" src="<?php echo $image ?>"></span></td>'+
			'<td id="rule-settings" class="prev next"><span class="rule-settings"><?php echo $this->__('To Date') ?></span><span><input style="width: 50px !important;" class="input-text rule-date" type="text" id="<?php echo $id ?>_{{option_id}}_to_date" name="<?php echo $name ?>[{{option_id}}][to_date]"  value="{{to_date}}"><img id="<?php echo $id ?>_{{option_id}}_to_date_trig" title="<?php echo $this->__('Date selector') ?>" class="v-middle" src="<?php echo $image ?>"></span></td>'+
			'<td id="rule-settings" class="prev next"><span class="rule-settings"><?php echo $this->__('Min Number of Friends') ?></span><span><input style="width: 25px !important;" type="text" class="input-text" id="<?php echo $id ?>_{{option_id}}_min_friends" name="<?php echo $name ?>[{{option_id}}][min_friends]"  value="{{min_friends}}"></span></td>'+
			'<td id="rule-settings" class="next last a-right"><?php echo $this->getAddButtonHtml() ?></td>'+
		'</tr>'+
   '</table>'+
    '<table class="border" cellpadding="0" cellspacing="0">'+
        '<input type="hidden" class="required-option-select-type-rows" name="validation_{{option_id}}_result_<?php echo $target ?>" value="" >'+
        '<thead>'+
        '<tr class="headings">'+
            '<th class="rule-head-auto"><?php echo $this->__('Discount Rule') ?> <span class="required">*</span></th>'+
            '<th><?php echo $this->__('Condition') ?> <span class="required">*</span></th>'+
            '<th class="last a-right type-butt"></th>'+
        '</tr>'+
        '</thead>'+
        '<tbody id="<?php echo $target; ?>_select_option_type_row_{{option_id}}">'+
        '</tbody>'+
    '</table>';

<?php echo $target; ?>OptionTemplateDynamicLevelsRow = 
    	'<tr id="<?php echo $id ?>_{{id}}_select_{{select_id}}">'+
            '<td class="rule-head-auto">'+
            '<input type="hidden" name="<?php echo $name ?>[{{id}}][values][{{select_id}}][option_type_id]" value="{{option_type_id}}">'+
            '<input type="hidden" id="<?php echo $id ?>_{{id}}_select_{{select_id}}_is_delete" name="<?php echo $name ?>[{{id}}][values][{{select_id}}][is_delete]" value="">'+
            '<?php echo $this->getDynamicDiscountRulesSelectHtml('dynamic_levels') ?>'+
            '<td><input type="text" class="input-text required-percent-level" id="<?php echo $id ?>_{{id}}_select_{{select_id}}_percent" name="<?php echo $name ?>[{{id}}][values][{{select_id}}][percent]" style="width: 50px ! important; margin-right: 5px;" value="{{percent}}"><small class="nobr">% of friends selected</small></td>'+
            '<td class="last a-right type-butt"><span title="<?php echo $this->__('Delete Level') ?>"><?php echo $this->getDeleteButtonHtml() ?></span></td>'+
        '</tr>';

<?php echo $target; ?>selectOptionType = {
    div : '<?php echo $target; ?>_select_option_type_row',
    itemCount : 0,
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : <?php echo $target; ?>OptionTemplateDynamicLevelsRow,
    add : function(data) {

        this.template = new Template(this.templateText, this.templateSyntax);

        if (data.target || data.srcElement) {//data is Event (work in IE and Firefox)
            element = $(Event.findElement(data, 'button'));
            optionId = element.readAttribute('id').sub('add_select_row_button_', '');
            data = {};
            data.option_type_id = '-1';
            data.select_id = this.itemCount;
        } else {
            optionId = data.option_id;
            data.select_id = data.option_type_id;
            this.itemCount = data.item_count;
        }

        data.id  = optionId;

        Element.insert($(this.div+'_'+data.id), {'bottom':this.template.evaluate(data)});
        stwHandleDiscounts('<?php echo $id ?>', true, data.id);
        if (data.discount_rule) {
            $A($('<?php echo $id ?>_'+data.id+'_select_'+data.select_id+'_discount_rule').options).each(function(option){
                if (option.value==data.discount_rule) option.selected = true;
            });
        }

        this.itemCount++;
        this.bindRemoveButtons();
    },
    remove : function(event){
        var element = $(Event.findElement(event, 'tr'));
        element.remove();
    },
    bindRemoveButtons : function(){
        var buttons = $$('.delete-select-row');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
				Event.observe(buttons[i], 'click', function(){
					this.up(2).remove();		
					this.remove.bind(this)
				})
            }
        }
    },
    bindAddButton : function()
    {
        var buttons = $$('.add-select-row');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.add.bind(this));
            }
        }
    }
}

if ($('option_panel_type_select')) {
    $('option_panel_type_select').remove();
}

<?php echo $target; ?>selectOptionType.bindRemoveButtons();

Validation.addAllThese([
    ['required-option-select-type-rows', '<?php echo $this->__('Please add a level.') ?>', function(v, elm) {
            var optionContainerElm = elm.up('div.grid');
            var selectTypesFlag = false;
            selectTypeElements = $$('#'+optionContainerElm.id+' .select-rule');
            selectTypeElements.each(function(elm){
                if (elm.id && elm.up('tr').visible()) {
                    selectTypesFlag = true;
                }
            });
            elm.advaiceContainer = optionContainerElm.id+'_advice';
        return selectTypesFlag;
}]]);

if($('add_select_row_button')){
    Event.observe('add_select_row_button', 'click', <?php echo $target; ?>selectOptionType.add.bind(<?php echo $target; ?>selectOptionType));
}
//]]>
</script>