<?php

/**
 * Add In Mage::
 *
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the EULA that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL: http://add-in-mage.com/support/presales/eula/
 *
 *
 * PROPRIETARY DATA
 * 
 * This file contains trade secret data which is the property of Add In Mage:: Ltd. 
 * This file is submitted to recipient in confidence.
 * Information and source code contained herein may not be used, copied, sold, distributed, 
 * sub-licensed, rented, leased or disclosed in whole or in part to anyone except as permitted by written
 * agreement signed by an officer of Add In Mage:: Ltd.
 * 
 * 
 * MAGENTO EDITION NOTICE
 * 
 * This software is designed for Magento Community edition.
 * Add In Mage:: Ltd. does not guarantee correct work of this extension on any other Magento edition.
 * Add In Mage:: Ltd. does not provide extension support in case of using a different Magento edition.
 * 
 * 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Add In Mage:: Ltd. (http://www.add-in-mage.com)
 * @license     http://add-in-mage.com/support/presales/eula/  End User License Agreement (EULA)
 * @author      Add In Mage:: Team <team@add-in-mage.com>
 */

$style = $this->getDateStyle();
$id = $this->getFieldId();
$image = $this->getSkinUrl('images/grid-cal.gif');
$name = $this->getFieldName();
$target = $this->_rule;
?>
<script type="text/javascript">
//<![CDATA[
<?php echo $target; ?>OptionTemplateFixed = '<table class="border" cellpadding="0" cellspacing="0">'+
'<tr class="headings">'+
	'<th class="type-last"><?php echo $this->__('Fixed Discount Rule') ?> <span class="required">*</span></th>'+
	'<th class="rule-head"><?php echo $this->__('From Date') ?></th>'+
	'<th class="rule-head"><?php echo $this->__('To Date') ?></th>'+
	'<th class="rule-head-last"><?php echo $this->__('Min Number of Friends') ?></th>'+
'</tr>'+
'<tr>'+
	'<td><?php echo $this->getDynamicDiscountRulesSelectHtml('fixed') ?></td>'+
	'<td><input type="text" style="width: 67% !important;" class="input-text rule-date" id="<?php echo $id ?>_{{option_id}}_from_date" name="<?php echo $name ?>[{{option_id}}][from_date]" value="{{from_date}}"><img id="<?php echo $id ?>_{{option_id}}_from_date_trig" title="<?php echo $this->__('Date selector') ?>" class="v-middle" src="<?php echo $image ?>"></td>'+
	'<td><input type="text" style="width: 67% !important;" class="input-text rule-date" id="<?php echo $id ?>_{{option_id}}_to_date" name="<?php echo $name ?>[{{option_id}}][to_date]" value="{{to_date}}"><img id="<?php echo $id ?>_{{option_id}}_to_date_trig" title="<?php echo $this->__('Date selector') ?>" class="v-middle" src="<?php echo $image ?>"></td>'+
	'<td align="right"><label style="font-size: 11px; font-weight: bold;  margin-right: 10px;">min: </label> <input class="input-text" style="width: 50px !important;" type="text" id="<?php echo $id ?>_{{option_id}}_min_friends" name="<?php echo $name ?>[{{option_id}}][min_friends]" value="{{min_friends}}"></td>'+
'</tr>'+
'</table>';
//]]>
</script>
