<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Facebook
 * @author      Ivan Weiler <ivan.weiler@gmail.com>
 * @copyright   Inchoo (http://inchoo.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<br />

<button rel="facebook-connect" class="facebook-button" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="button">&nbsp;</button>
<!--
	<div class="content new-users" style="margin-bottom:30px">
	  
		<p><?php echo $this->__('Note:By logging in with facebook,you also agree to join the Legacy Row newsletter.You may unsubscribe from the newsletter at any time.' ) ?></p>
	</div>
   
-->
</div>
