<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Facebook
 * @author      Ivan Weiler <ivan.weiler@gmail.com>
 * @copyright   Inchoo (http://inchoo.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<br />
<div class="account-login facebook-login">
    <!--<div class="page-title">
        <h1><?php echo $this->__('Connect with Facebook') ?></h1>
    </div>-->
    <div class="buttons-set">
		<button rel="facebook-connect" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="button">&nbsp;</button>
	</div>

	<div class="content new-users" style="min-height: 100px;">
		<!--<h2><?php echo $this->__('Facebook Users') ?></h2>-->
		<p><?php echo $this->__('Note:By logging in with facebook,you also agree to join the Cempori newsletter.You may unsubscribe from the newsletter at any time.' ) ?></p>
	</div>
    
	
</div>
